name: Update RSS Feed
on:
  schedule:
    - cron: "0 */6 * * *"  # Каждые 6 часов
  workflow_dispatch:  # Ручной запуск
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser requests beautifulsoup4 html2text selenium==4.9.0 webdriver-manager
          python -m pip show selenium
          python -m pip list
          # Устанавливаем Google Chrome
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          # Проверяем, что Chrome установлен
          google-chrome --version
      - name: Run script
        run: python rss_parser.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated RSS feed" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
